services:

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "9090:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080


  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: kafka-producer-api
    depends_on:
      - kafka
    restart: on-failure
    env_file: ./.env  # Load env vars into the container
    volumes:
      - ./api:/app  # Optional: allow live-editing code
    command: ["python", "producer.py"]

  simulator:
    build: ./api-simulator
    container_name: external-api-simulator
    ports:
      - "5001:5001"
    restart: on-failure

  # ml-trainer:
  #   build: ./ml
  #   container_name: ml-trainer
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env


volumes:
  pgdata:
